---
# tasks file for zabbix
- name: Actualizar idioma
  become: yes
  copy: src=locale.gen dest=/etc/

- name: Comando
  become: yes
  shell: |
   sudo locale-gen "en_US"

- name: conseguir
  become: yes
  command: wget https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb

- name: respositorio
  become: yes
  command: dpkg -i zabbix-release_6.0-1+debian11_all.deb

- name: respositorio
  become: yes
  command: sudo apt update

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
   - zabbix-server-mysql
   - zabbix-frontend-php
   - zabbix-nginx-conf
   - zabbix-sql-scripts
   - zabbix-agent

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
   - mariadb-server


- name: Comando
  become: yes
  shell: |
   systemctl start mariadb

- name: Comando
  become: yes
  shell: |
   systemctl enable mariadb

- name: Comando
  become: yes
  shell: |
   mysql -uroot -p'rootDBpass' -e "create database zabbix character set utf8mb4 collate utf8mb4_bin;"

- name: Comando
  become: yes
  shell: |
   mysql -uroot -p'rootDBpass' -e "grant all privileges on zabbix.* to zabbix@localhost identified by 'zabbixDBpass';"

- name: Comando
  become: yes
  shell: |
   zcat /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz | mysql -uzabbix -p'zabbixDBpass' zabbix

- name: chmod
  become: yes
  command: chmod -R 777 /etc/zabbix   

- name: Actualizar
  become: yes
  copy: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf


- name: Actualizar
  become: yes
  copy: src=nginx.conf dest=/etc/zabbix/nginx.conf

- name: Actualizar
  become: yes
  copy: src=default dest=/etc/nginx/sites-available/default

- name: Comando
  become: yes
  shell: |
   systemctl restart zabbix-server zabbix-agent 

- name: Comando
  become: yes
  shell: |
   systemctl enable zabbix-server zabbix-agent

- name: echo
  become: yes
  command: echo "date.timezone = Europe/Madrid" >> /etc/php/7.4/apache2/php.ini

- name: chmod
  become: yes
  command: chmod 777 /etc/zabbix/web

- name: php
  become: yes
  copy: src=zabbix.conf.php dest=/etc/zabbix/web/zabbix.conf.php

- name: Comando
  become: yes
  shell: |
   sudo apachectl stop
  
- name: Comando
  become: yes
  shell: |
   sudo systemctl restart zabbix-server zabbix-agent nginx php7.4-fpm

- name: Comando
  become: yes
  shell: |
   sudo systemctl enable zabbix-server zabbix-agent nginx php7.4-fpm